// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqlevpkeneqlqgqagmxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxbGV2cGtlbmVxbHFncWFnbXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDE2MTgsImV4cCI6MjA1ODU3NzYxOH0.Dr33Cf5xervpKIOM4QXalsiDtIr3zsvR5BhPZoWDqDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);